@ECHO OFF

echo AUTHENTIQ_DB_HOST: %AUTHENTIQ_DB_HOST%
echo AUTHENTIQ_DB_PORT: %AUTHENTIQ_DB_PORT%
echo AUTHENTIQ_DB_NAME: %AUTHENTIQ_DB_NAME%
echo AUTHENTIQ_DB_USERNAME: %AUTHENTIQ_DB_USERNAME%
echo AUTHENTIQ_DB_PASSWORD: %AUTHENTIQ_DB_PASSWORD%

echo AUTHENTIQ_ADMIN_USERNAME: %AUTHENTIQ_ADMIN_USERNAME%
echo AUTHENTIQ_ADMIN_PASSWORD: %AUTHENTIQ_ADMIN_PASSWORD%